# Lang
language: en

# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: 无肉不欢，老树叶
description: 个人博客，学习记录.

links:
  Blog: /archives
  GitHub: https://github.com/yeqinfu
#  Instagram: http://instagram.com/
#  Facebook: http://facebook.com/
#  Twitter : http://twitter.com/

archive_footer_content:老铁，我是底线
post_footer_content:老铁，我是底线
# Info
#archive_footer_content: Lorem ipsum dolor sit amet, **consectetur adipiscing elit.** Fusce eget urna vitae velit *eleifend interdum at ac nisi. In nec ligula lacus. Cum sociis natoque* penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu cursus erat, ut dapibus quam. Archive
#post_footer_content: ipsum dolor sit amet, **consectetur adipiscing elit.** Fusce eget urna vitae velit *eleifend interdum at ac nisi. In nec ligula lacus. Cum sociis natoque* penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu cursus erat, ut dapibus quam. Post
