# Simple workflow for deploying static content to GitHub Pages
name: 静态网站发布

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
      # 设置 node.js 环境
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'  
      - name: Install hexo dependencies
      # 下载 hexo-cli 脚手架及相关安装包
        run: |
          npm install -g hexo-cli
          npm install
      - name: Generate files
      # 编译 markdown 文件
        run: |
          hexo clean
          hexo generate
      - name: Deploy hexo blog
        env: 
          # Github 仓库
          GITHUB_REPO: github.com/yeqinfu/yeqinfu.github.io
        run: |
          cd ./public && git init && git add .
          git config user.name "yeqinfu"
          git config user.email "990761790@qq.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://${{ secrets.token }}@$GITHUB_REPO" master:master
